# Generated by Django 5.1.3 on 2025-07-27 17:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture (JPG, PNG, max 5MB)', null=True, upload_to=users.models.user_profile_image_path),
        ),
    ]
