# Generated by Django 5.1.3 on 2025-07-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comparison_session',
            },
        ),
        migrations.CreateModel(
            name='ComparedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('comparison_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_products', to='comparison.comparisonsession')),
            ],
            options={
                'db_table': 'compared_product',
                'unique_together': {('comparison_session', 'product')},
            },
        ),
    ]
