# Generated by Django 5.1.3 on 2024-11-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('stock', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search.search')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'ordering': ['price'],
                'indexes': [models.Index(fields=['price'], name='search_sear_price_38dac4_idx'), models.Index(fields=['-price'], name='search_sear_price_1d3945_idx'), models.Index(fields=['rating'], name='search_sear_rating_ef1c8a_idx'), models.Index(fields=['-rating'], name='search_sear_rating_a2f6a1_idx')],
            },
        ),
    ]
