# Generated by Django 5.1.3 on 2025-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
