# Generated by Django 5.1.3 on 2024-11-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name']},
        ),
    ]
