# Generated by Django 5.1.3 on 2024-11-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='featuredproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_src',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
